trigger:
  - master

pool:
  name: 'Ubuntu'

steps:
  - task: GitVersion@5
    inputs:
      runtime: 'core'
      preferBundledVersion: false
      configFilePath: 'GitVersion.yml'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/src'
      ArtifactName: 'drop'
      publishLocation: 'Container'